FLASK_APP:
  PORT: 5010
  SECRET_KEY: dev
  SESSION_COOKIE_SECURE: True
  SESSION_COOKIE_HTTPONLY: True
  SESSION_COOKIE_SAMESITE: Strict
  MAX_MYLOTO_COUNT_PAID_LEVEL1: 20

DATABASE:
  DB_HOST: 'localhost:5410'
  DB_USER: postgres
  DB_PASS: admin
  DB_NAME: lottery

AUTH:
  AUTH_HOST: 192.168.10.100:5000
  ACCESS_TOKEN_PUBLIC_KEY: configs/secret/public_rsa2048.pem
